services:
    laravel.test:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    postgres:
        image: "postgres"
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        networks:
            - sail
        ports:
            - "${FORWARD_POSTGRES_PORT:-5432}:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data

    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "finance@email.com"
            PGADMIN_DEFAULT_PASSWORD: "finance"
        networks:
            - sail
        ports:
            - "54321:80"
        depends_on:
            - postgres
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    dbdata:
        driver: local
